- name: hostname check unx
  hosts: all
  gather_facts: no
  vars:
    inv_hname: "{{ inventory_hostname | lower }}"
    #hostname: "{{ inventory_hostname.split(.)[0] | lower }}"

  tasks:
  - name: Get host name
    shell: uname -n | cut -d"." -f1
    register: hostname

  - name: Show hostname on host
    debug: var=hostname.stdout_lines

  - name: Show hostname in inventory
    debug:
      msg: "{{ inv_hname }} {{ hostname.stdout.rstrip() | lower }}"

  - name: Msg when hostnames match
    debug:
      msg: "OK  {{ inv_hname }} {{ inventory_hostname.rstrip() | lower }}"
    when: hname == (hostname.stdout_lines.rstrip() | lower)

  - name: Msg when hostnames does not match
    debug:
      msg: "Hostname is not the same {{ inv_hname }} {{ inventory_hostname.rstrip() | lower }}"
    when: hname != hostname.stdout_lines.rstrip() | lower

