- name: hostname check unx
  hosts: all
  gather_facts: no
  vars:
    inv_hname: "{{ inventory_hostname | lower }}"
    #hostname: "{{ inventory_hostname.split(.)[0] | lower }}"

  tasks:
    - name: Get Real Hostname
      shell: uname -n | cut -d"." -f1
      register: real_hostname_output
      changed_when: false

    - name: Display Hostname
      debug:
        msg: "Hostname in inventory is {{ inventory_hostname }} . Real hostname is {{ real_hostname_output.stdout_lines }}"

    - name: Compare Hostnames
      assert:
        that:
          - ansible_hostname == real_hostname_output.stdout
        msg: "Hostnames do not match! ansible_hostname: {{ inventory_hostname }}, real_hostname: {{ real_hostname_output.stdout_lines }}"


