- name: hostname check unx
  hosts: all
  gather_facts: no
  vars:
  hostname: "{{ inventory_hostname.split(.)[0] | lower }}"

  tasks:
  - name: Get host name
    shell: uname -n | cut -d"." -f1
    register: hostname

  - name: Show var
    debug: var=hostname.stdout_lines

  - name: Show hostname
    debug:
      msg: "{{ hostname }} {{ hostname.stdout.rstrip() | lower }}"

  - name: Msg when hostnames match
    debug:
      msg: "OK  {{ hostname }} {{ inventory_hostname.strip() | lower }}"
    when: hostname == (hostname.stdout.rstrip() | lower)

  - name: Msg when hostnames does not match
    debug:
      msg: "Hostname is not the same {{ hostname }} {{ hostname.stdout.rstrip() | lower }}"
    when: hostname != hostname.stdout.rstrip() | lower

